steps:
  - name: node:16
    entrypoint: npm
    args: ["install"]
  - name: node
    entrypoint: npm
    args: ["run"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "builds",
        "submit",
        "--image=gcr.io/ichowkidar/cloudrun-main-service",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "cloudrun-main-service",
        "--region=asia-south2",
        "--platform=managed",
        "--image=gcr.io/ichowkidar/cloudrun-main-service:$SHORT_SHA",
      ]
    timeout: 1200s
