steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ichowkidar/nodeexample:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ichowkidar/nodeexample:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'nodeexample', '--region=asia-south2', '--platform=managed', '--image=gcr.io/ichowkidar/nodeexample:$SHORT_SHA']
